
name: CI Build

on: [push, pull_request]

jobs:   
  build-modern:
    name: FBA for MiyooCFW (uClibc)
    runs-on: ubuntu-20.04
    container:
      image: nfriedly/miyoo-toolchain:steward
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: make -f Makefile
    - uses: actions/upload-artifact@v3
      with:
        name: FBA binary
        path: bin/fba
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`
