
name: CI Build

on: [push, pull_request]

jobs:   
  build-modern:
    name: FBA for MiyooCFW (musl)
    runs-on: ubuntu-22.04
    container:
      image: miyoocfw/toolchain-static-musl:master
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: make -j$(nproc) && make ipk
    - uses: actions/upload-artifact@v4
      with:
        name: FBA binary
        path: bin/fba
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`
    - uses: actions/upload-artifact@v4
      with:
        name: FBA package (IPK)
        path: fba.ipk
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`
